import fetch from "node-fetch";
import fs from "fs";
import { PublicClientApplication, LogLevel } from "@azure/msal-node";
const TENANT="1557f771-4c8e-4dbd-8b80-dd00a88e833e", CLIENT_ID="51f81489-12ee-4a9e-aaae-a2591f45987d", ORG="https://orgd90897e4.crm.dynamics.com";
const cachePlugin = { beforeCacheAccess: async(ctx)=>{ if(fs.existsSync('.token-cache.json')) ctx.tokenCache.deserialize(fs.readFileSync('.token-cache.json','utf8')); }, afterCacheAccess: async(ctx)=>{ if(ctx.cacheHasChanged) fs.writeFileSync('.token-cache.json', ctx.tokenCache.serialize()); } };
const pca = new PublicClientApplication({ auth:{ clientId:CLIENT_ID, authority:`https://login.microsoftonline.com/${TENANT}`}, cache:{cachePlugin}, system:{loggerOptions:{logLevel:LogLevel.Error}}});
const accounts = await pca.getTokenCache().getAllAccounts();
const r = await pca.acquireTokenSilent({account:accounts[0], scopes:[`${ORG}/.default`]});
const tok = r.accessToken;
const pub = await fetch(ORG+"/api/data/v9.2/PublishAllXml",{method:'POST',headers:{Authorization:'Bearer '+tok,'Content-Type':'application/json'}});
console.log('publish:', pub.status);
